source 'https://rubygems.org'

gem 'sinatra', '~> 1.4.2' 
gem 'sinatra-contrib'
gem "haml", '~> 4.0.2'
gem "sass", '~> 3.2.8'
gem 'weibo_2', '~> 0.1.4'
gem 'time_ago_in_words', '~> 0.1.0'
gem 'json', '~> 1.7.7'
gem 'rest-client'
